### ISSUE TITLE
Heap overflow detected

### ISSUE THREAD

**Issue by fsjack** [iosdevzone/IDZSwiftCommonCrypto#19]
Hi,
Tried these code below would encountered a crash accidentally. If turn on '**Enable Address Sanitizer**' then would constantly encounter a **Heap Overflow Detected** crash.

```
let array: [UInt8] = [1, 2, 3, 4, 5]
NSData(bytes: array, length: array.count).MD5
```

The behavior seem totally depend on how the NSData construct, It won't crash if data come from a string or other way whatsoever.

**Comment by iosdevzone** [comment]
Hi Jackie, thanks for reporting this issue. It is not clear to me just yet whether this is a problem with Swift, NSData or IDZSwiftCommonCrypto. 

The issue seems to occur on the following line in Crypto.swift:

```swift
        let data = self.dynamicType.init(bytes: result, length: result.count)
```

and occurs during a WRITE in `-[_NSInlineData initWithBytes:length:]`

I'll try to narrow it down over the next few days as time allows.

Cheers,
idz

**Comment by iosdevzone** [comment]
I have made a small test project that does not include `IDZCommonCrypto` and demonstrates that this is a Swift/NSData issue. As soon as I can I will file a radar with Apple and update this issue with the radar number.

**Comment by fsjack** [comment]
Thanks for reply :] 
Seem Swift is vulnerable on dynamic dispatcher.
I will close the issue now.
