### ISSUE TITLE
CocoaPods caches CommonCrypto.framework after first `pod install`

### ISSUE THREAD

**Issue by codecaffeine** [iosdevzone/IDZSwiftCommonCrypto#83]
I use IDZSwiftCommonCrypto via CocoaPods. When I upgraded to Xcode 9.3 and tried to run the app, it started giving me `module.map` errors. I looked at the `module.map` and the path it referenced was wrong:
```
module CommonCrypto [system] {
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/include/CommonCrypto//CommonCrypto.h"
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/include/CommonCrypto//CommonRandom.h"
  export *
}
```

It referenced `iPhoneSimulator11.2.sdk` instead of `iPhoneSimulator11.3.sdk` which is used in Xcode 9.3. It turns out, CocoaPods caches this `modulemap` only when you first run `pod install`:
`cat ~/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.10.0-4eef2/Frameworks/iphonesimulator/CommonCrypto.framework/module.map`. Each subsequent `pod install` will just pull that framework/module.map

The current work around is to run `pod cache clean IDZSwiftCommonCrypto; rm -rf Pods; pod install` when you upgrade Xcode.

I’m not sure if this is possible, but it might be good to prevent CocaPods from caching that framework that gets created. Another option would be to have it reference `iPhoneSimulator.sdk` and not the SDK specific version `iPhoneSimulator11.2.sdk`. The code generating that path is [here](https://github.com/iosdevzone/IDZSwiftCommonCrypto/blob/2e58af96ef1c2b960748c8d24fcfe4e3c57181d7/GenerateCommonCryptoModule.swift#L77)

**Comment by iosdevzone** [comment]
I agree it's annoying, but the current solution is the best I could do. 

As I argued to the CocoaPods folks the `prepare_command` should probably be run at `pod install` time and anything it produces should not be cached. A large number of CocoaPods user do not realize that the cache even exists (myself included until this issue came to light), the messages it prints do not (or at least did not) make it clear that pod is using files from the cache and the documentation does not mention that the prepare command is only run on first download. They see things differently see (https://github.com/CocoaPods/CocoaPods/issues/7192) and I am not sufficiently adept at ruby to do a pull request. There's no way in the `podspec` to avoid the caching. In the discussion of this issue there was mention of an upcoming `script_phase` option to be added to CocoaPods. I am not sure if this is available in the currently released version. 

The path used by the script is the result of running the `xcrun --sdk iphoneos --show-sdk-path` command. Currently this returns the version specific path. To be honest, I never noticed the existence of the soft link you mentioned. I suppose I could remove the version, test that file exists and use that path if it does, but that seems a bit ugly. 

I'll check if the `script_phase` field is available as soon as I get a moment. I think it's the best of all the solutions.

**Comment by iosdevzone** [comment]
Now that CommonCrypto is an official framework, this should no longer be an issue.
