### ISSUE TITLE
No automatic padding for IV

### ISSUE THREAD

**Issue by mjholgate** [iosdevzone/IDZSwiftCommonCrypto#95]
I think this is a bug, but I'm not 100% sure.

The documentation gives an example:

`var cryptor = Cryptor(operation:.encrypt, algorithm:.aes, options:.PKCS7Padding, key:key, iv:Array<UInt8>())
`

However, this causes a read from uninitialised memory when 'iv' is bridged to be an UnsafeRawPointer, generating random results.

I notice that the key is zero-padded:

`        self.init(operation:operation, algorithm:algorithm, options:options, keyBuffer:zeroPad(array: key, blockSize: paddedKeySize), keyByteCount:paddedKeySize, ivBuffer:iv)`

Should this also be done for the IV? Or at least should the documentation be updated to pass in the correct size buffer? There is no compiler warning because of the bridge to UnsafeRawPointer.

Thanks!

**Comment by iosdevzone** [comment]
Sorry it's taken me so long to get this... This certainly looks a bit suspicious. Thanks for pointing it out. I'll look into and get back to you.

**Comment by iosdevzone** [comment]
Thanks again for prodding me to take action on this. 

Since it's important to generate random initialization vectors, I choose not to pad out the IV if it was too small. It seemed to me it might encourage people to be lazy and just pass a zero vector all the time. So now the library will `fatalError` if the IV is not the correct size. 

To enjoy this new strictness just upgrade to version 0.12.1!

**Comment by mjholgate** [comment]
Nice one @iosdevzone, thanks. In my case I am using the key once only, so I think a zero IV is safe. But I agree it's better to make fatalError() in the case to make the user aware of what they are doing.
